name: 部署DTY站点dty

on:
  push:
    branches:
      - www.datangyuan.cn  # 仅在 www.datangyuan.cn 分支推送时触发，根据实际情况修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to www.datangyuan.cn-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b www.datangyuan.cn-pages
          git rm -rf .
          cp -r dist/. .
          git add .
          git commit -m "Deployed latest changes"
          git push --force origin www.datangyuan.cn-pages

      - name: 添加华为云服务器主机密钥到已知主机文件
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HUAWEI_CLOUD_SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: 同步到华为云
        if: success()
        env:
          HUAWEI_CLOUD_SERVER_IP: ${{ secrets.HUAWEI_CLOUD_SERVER_IP }}
          HUAWEI_CLOUD_SERVER_USER: ${{ secrets.HUAWEI_CLOUD_SERVER_USER }}
          HUAWEI_CLOUD_SERVER_PASSWORD: ${{ secrets.HUAWEI_CLOUD_SERVER_PASSWORD }}
          HUAWEI_CLOUD_SERVER_DIR: ${{ secrets.HUAWEI_CLOUD_SERVER_DIR }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client sshpass
          sshpass -p "${HUAWEI_CLOUD_SERVER_PASSWORD}" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/ "${HUAWEI_CLOUD_SERVER_USER}@${HUAWEI_CLOUD_SERVER_IP}:${HUAWEI_CLOUD_SERVER_DIR}"
